### ISSUE TITLE
Automatic script to get all members?

### ISSUE THREAD

**Issue by PragTob** [shoes/shoesrb.com#72] opened 2014-11-28 15:30 UTC
Right now the contributord page is rather static and we are missing out on some people but I still want to appreciate and share the love with/for EVERYONE!

it was discussed before to write a little script to load the contributors from github.

Related discussions #7 #71

**Comment by JesseHerrick** [comment] 2014-11-28 19:03
My first thought is GitHub's API. The problem is getting the data client-side because it's cross domain. But GitHub's API supports CORS and JSON-P, so I'll see what I can whip up in JS.
In cURL:

```
$ curl -i https://api.github.com/repos/shoes/shoes4/contributors
```

**Comment by JesseHerrick** [comment] 2014-11-28 21:31
Here's [my solution](http://jsbin.com/refosi/1/edit?html,output). It uses [GitHub's API](https://developer.github.com/v3/repos/collaborators/) through JSON-P to bypass cross domain errors.

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>GitHub API Test</title>
  </head>
  <body>
  <h1>Contributors</h1>
  <ul id="contributors">
  </ul>

  <script>
  var shoes = function(github) {
    var contributors = github.data;
    var list = document.getElementById('contributors');

    for (var i = 0; i < contributors.length; i++) {
      var username = contributors[i].login;
      var contributions = contributors[i].contributions;

      var item = document.createElement('li');
      item.innerHTML = username + ' (' + contributions + ')';
      list.appendChild(item);
    }
  };
  </script>
  <script src="https://api.github.com/repos/shoes/shoes4/contributors?callback=shoes"></script>
  </body>
</html>
```

**Comment by nicholalexander** [comment] 2017-11-30 14:39
@PragTob / @JesseHerrick  - is there any continued interest in this?  I think building it on the front end is interesting.  But we could also pull the data down into a data file for jekyll and then display it with the liquid templates.  That would make it easy to customize any specific instances of people being in or not in the lists based on the history of the project.  

Also, since the Shoes org has brought the shoes projects under the fold and has what appears to be an up to date list of public members, one could build a "core team" list off that and then a separate page with contributors to all the sub repos displayed by commit count or randomly or whatever.   

If any of this is of interest, I'd love to work on it.  I think the net effect of this would be to make it clear how big and welcoming the shoes community is - which seems like a great thing to showcase as prominently as possible!  Let me know!

**Comment by jasonrclark** [comment] 2017-12-01 04:47
If that sounds interesting to you @nicholalexander, feel free to give it a shot. I've worked plenty with Jekyll data, and that's very workable but if trying from the front-end appeals, go for it!

**Comment by nicholalexander** [comment] 2018-01-17 17:25
Unless anything is outstanding from #89, I think we can close this issue!

**Comment by jasonrclark** [comment] 2018-01-18 04:14
💥

**Closed as completed by jasonrclark** 2018-01-18 04:14 UTC
